#!/usr/bin/env python3
"""Extract contents/work entities from MARC 505 fields using rule-based parsing.

MARC 505 (formatted contents note) follows a highly regular pattern:
    1) דף 1א-176ב: ויטל, חיים בן יוסף: אוצרות חיים.
    2) דף 180א-181א: ויטל, חיים בן יוסף: עץ חיים (קטע).

This script parses the numbered structure to extract:
    - WORK: Work titles
    - FOLIO: Folio ranges (דף Xא-Yב)
    - WORK_AUTHOR: Author of the specific work

Additional training data is generated by cross-referencing 505 work titles
in 500$a general notes (Strategy C).

Output: JSONL files compatible with the NER training pipeline.
"""

import json
import logging
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.FileHandler("contents_extraction.log"),
        logging.StreamHandler(sys.stdout),
    ],
)
logger = logging.getLogger(__name__)


# ── Regex patterns for 505 parsing ───────────────────────────────────

# Folio range: "דף 1א-176ב", "דפים [3]א-[34]א", "דף 82א"
FOLIO_PATTERN = re.compile(
    r"(דף(?:ים)?\s*\[?\d+\]?[אב]?(?:\s*[-–]\s*\[?\d+\]?[אב]?)?)"
)

# Item number: "1)" at start or after pipe
ITEM_SPLIT_PATTERN = re.compile(r"(?:^|\|)\s*(\d+)\)\s*")

# Author-title separator: "Author, Given ben Father: Work Title"
# The colon after author name (before title) is the key delimiter
AUTHOR_TITLE_COLON = re.compile(r"^([^:]{3,60}):\s+(.+)$")

# Name indicators (to distinguish author from title in ambiguous cases)
NAME_INDICATORS = re.compile(r"[,]|בן |בת |אבן |הכהן|הלוי|ב\"ר|בכ\"ר")


class ContentsEntityExtractor:
    """Extract structured work, folio, and author entities from MARC 505."""

    def __init__(self, input_file: Path) -> None:
        self.input_file = input_file
        self.stats: dict[str, Any] = {
            "total_rows": 0,
            "rows_with_505": 0,
            "total_items_parsed": 0,
            "items_with_folio": 0,
            "items_with_author": 0,
            "items_with_title": 0,
            "samples_created": 0,
            "cross_ref_samples": 0,
            "entities_by_type": Counter(),
        }

    def clean_marc_text(self, text: str) -> str:
        """Clean MARC field text."""
        if pd.isna(text) or not isinstance(text, str):
            return ""
        text = text.strip("\"'").strip()
        text = re.sub(r"\|\|", "|", text)
        text = re.sub(r"\s+", " ", text)
        return text.strip()

    def normalize_hebrew(self, text: str) -> str:
        """Normalize Hebrew text for matching."""
        if not text:
            return ""
        text = re.sub(r"[\u0591-\u05C7]", "", text)
        text = re.sub(r"\s+", " ", text)
        text = text.replace('"', "").replace("'", "").replace("`", "")
        return text.strip()

    def tokenize(self, text: str) -> list[str]:
        """Tokenize text preserving meaningful punctuation."""
        return text.split()

    def find_span_in_tokens(
        self, tokens: list[str], entity_text: str,
    ) -> tuple[int, int]:
        """Find entity span in tokenized text."""
        entity_norm = self.normalize_hebrew(entity_text)
        entity_words = entity_norm.split()
        if not entity_words:
            return (-1, -1)

        tokens_norm = [self.normalize_hebrew(t) for t in tokens]

        for i in range(len(tokens_norm) - len(entity_words) + 1):
            match = True
            for j, ew in enumerate(entity_words):
                tn = tokens_norm[i + j]
                if ew not in tn and tn not in ew:
                    match = False
                    break
            if match:
                return (i, i + len(entity_words))

        return (-1, -1)

    def parse_505_entry(self, text_505: str) -> list[dict]:
        """Parse a MARC 505 field into individual content items.

        Each item contains optional folio, author, and title fields.
        """
        items: list[dict] = []

        # Split by item numbers: "1) ... |2) ... |3) ..."
        parts = ITEM_SPLIT_PATTERN.split(text_505)
        # parts alternates: [pre-text, num1, text1, num2, text2, ...]
        segments: list[str] = []
        i = 1
        while i < len(parts):
            if i + 1 < len(parts):
                segments.append(parts[i + 1].strip().rstrip(".|"))
            i += 2

        # If no numbered items found, treat the whole text as one item
        if not segments and text_505.strip():
            segments = [text_505.strip()]

        for seg in segments:
            seg = seg.strip()
            if not seg or len(seg) < 3:
                continue

            item: dict[str, str] = {}
            remaining = seg

            # Extract folio range
            folio_match = FOLIO_PATTERN.match(remaining)
            if folio_match:
                item["folio"] = folio_match.group(1).strip()
                remaining = remaining[folio_match.end():].strip()
                # Remove leading colon/separator
                remaining = remaining.lstrip(":").strip()
                self.stats["items_with_folio"] += 1

            # Split author:title at colon
            colon_match = AUTHOR_TITLE_COLON.match(remaining)
            if colon_match:
                potential_author = colon_match.group(1).strip()
                potential_title = colon_match.group(2).strip().rstrip(".")

                # Verify author looks like a name
                if NAME_INDICATORS.search(potential_author):
                    item["author"] = potential_author
                    item["title"] = potential_title
                    self.stats["items_with_author"] += 1
                else:
                    # Could be "subtitle: rest" — treat whole as title
                    item["title"] = remaining.rstrip(".")
            else:
                item["title"] = remaining.rstrip(".")

            if item.get("title"):
                self.stats["items_with_title"] += 1

            self.stats["total_items_parsed"] += 1
            items.append(item)

        return items

    def create_bio_sample_from_item(
        self, segment_text: str, item: dict,
    ) -> dict | None:
        """Create a BIO-tagged sample from a single content item."""
        tokens = self.tokenize(segment_text)
        if len(tokens) < 2 or len(tokens) > 150:
            return None

        ner_tags = ["O"] * len(tokens)
        occupied: set[int] = set()
        entities_found: list[dict] = []

        # Label folio range
        if item.get("folio"):
            start, end = self.find_span_in_tokens(tokens, item["folio"])
            if start >= 0:
                span = set(range(start, end))
                if not (span & occupied):
                    occupied |= span
                    ner_tags[start] = "B-FOLIO"
                    for i in range(start + 1, end):
                        ner_tags[i] = "I-FOLIO"
                    entities_found.append({"text": item["folio"], "type": "FOLIO"})
                    self.stats["entities_by_type"]["FOLIO"] += 1

        # Label author
        if item.get("author"):
            start, end = self.find_span_in_tokens(tokens, item["author"])
            if start >= 0:
                span = set(range(start, end))
                if not (span & occupied):
                    occupied |= span
                    ner_tags[start] = "B-WORK_AUTHOR"
                    for i in range(start + 1, end):
                        ner_tags[i] = "I-WORK_AUTHOR"
                    entities_found.append({
                        "text": item["author"], "type": "WORK_AUTHOR",
                    })
                    self.stats["entities_by_type"]["WORK_AUTHOR"] += 1

        # Label title
        if item.get("title"):
            start, end = self.find_span_in_tokens(tokens, item["title"])
            if start >= 0:
                span = set(range(start, end))
                if not (span & occupied):
                    occupied |= span
                    ner_tags[start] = "B-WORK"
                    for i in range(start + 1, end):
                        ner_tags[i] = "I-WORK"
                    entities_found.append({"text": item["title"], "type": "WORK"})
                    self.stats["entities_by_type"]["WORK"] += 1

        if not entities_found:
            return None

        return {
            "tokens": tokens,
            "ner_tags": ner_tags,
            "entities": entities_found,
            "entity_count": len(entities_found),
            "notes_text": segment_text,
            "source_field": "505$a",
        }

    def extract_from_505(self, text_505: str) -> list[dict]:
        """Extract BIO-tagged samples from a single 505 field."""
        items = self.parse_505_entry(text_505)
        samples: list[dict] = []

        for item in items:
            # Reconstruct the text segment for this item
            parts: list[str] = []
            if item.get("folio"):
                parts.append(item["folio"] + ":")
            if item.get("author"):
                parts.append(item["author"] + ":")
            if item.get("title"):
                parts.append(item["title"])
            segment_text = " ".join(parts)

            if len(segment_text) < 5:
                continue

            sample = self.create_bio_sample_from_item(segment_text, item)
            if sample:
                samples.append(sample)

        return samples

    def cross_reference_in_notes(
        self, row: pd.Series, work_titles: list[str],
    ) -> list[dict]:
        """Find work titles from 505 in 500$a general notes (Strategy C)."""
        extra_samples: list[dict] = []

        if "500$a" not in row.index or pd.isna(row["500$a"]):
            return extra_samples

        notes_text = self.clean_marc_text(str(row["500$a"]))
        if not notes_text or len(notes_text) < 20:
            return extra_samples

        notes_norm = self.normalize_hebrew(notes_text)

        for title in work_titles:
            title_norm = self.normalize_hebrew(title)
            if not title_norm or len(title_norm) < 3:
                continue

            if title_norm in notes_norm:
                # Found work title in general notes — create training sample
                # Split notes at pipes and find the segment containing the title
                for segment in notes_text.split("|"):
                    segment = segment.strip()
                    if not segment:
                        continue
                    seg_norm = self.normalize_hebrew(segment)
                    if title_norm not in seg_norm:
                        continue

                    tokens = self.tokenize(segment)
                    if len(tokens) < 3 or len(tokens) > 100:
                        continue

                    ner_tags = ["O"] * len(tokens)
                    start, end = self.find_span_in_tokens(tokens, title)
                    if start < 0:
                        continue

                    ner_tags[start] = "B-WORK"
                    for i in range(start + 1, end):
                        ner_tags[i] = "I-WORK"

                    extra_samples.append({
                        "tokens": tokens,
                        "ner_tags": ner_tags,
                        "entities": [{"text": title, "type": "WORK"}],
                        "entity_count": 1,
                        "notes_text": segment,
                        "source_field": "500$a",
                    })
                    self.stats["cross_ref_samples"] += 1
                    self.stats["entities_by_type"]["WORK_crossref"] += 1
                    break  # One sample per title per note field

        return extra_samples

    def extract_from_record(self, row: pd.Series) -> list[dict]:
        """Extract contents entities from a single MARC record."""
        samples: list[dict] = []

        if "505$a" in row.index and pd.notna(row["505$a"]):
            text_505 = self.clean_marc_text(str(row["505$a"]))
            if text_505 and len(text_505) >= 10:
                self.stats["rows_with_505"] += 1
                bio_samples = self.extract_from_505(text_505)
                samples.extend(bio_samples)

                # Cross-reference work titles in 500 notes
                work_titles = [
                    e["text"]
                    for s in bio_samples
                    for e in s.get("entities", [])
                    if e["type"] == "WORK"
                ]
                if work_titles:
                    xref_samples = self.cross_reference_in_notes(row, work_titles)
                    samples.extend(xref_samples)

        return samples

    def process_dataset(self, max_rows: int | None = None) -> list[dict]:
        """Process the entire MARC dataset."""
        logger.info("Loading %s...", self.input_file)
        df = pd.read_csv(self.input_file, low_memory=False)
        logger.info("Loaded %d records", len(df))

        all_samples: list[dict] = []
        limit = max_rows or len(df)

        for idx in range(min(limit, len(df))):
            row = df.iloc[idx]
            self.stats["total_rows"] += 1
            samples = self.extract_from_record(row)
            all_samples.extend(samples)

            if (idx + 1) % 10000 == 0:
                logger.info(
                    "Processed %d/%d rows, %d samples so far",
                    idx + 1, limit, len(all_samples),
                )

        self.stats["samples_created"] = len(all_samples)
        return all_samples

    def save_results(self, samples: list[dict], output_dir: Path) -> None:
        """Save extracted samples to JSONL and statistics to JSON."""
        output_dir.mkdir(parents=True, exist_ok=True)

        output_file = output_dir / "contents_dataset.jsonl"
        with open(output_file, "w", encoding="utf-8") as f:
            for sample in samples:
                f.write(json.dumps(sample, ensure_ascii=False) + "\n")
        logger.info("Saved %d samples to %s", len(samples), output_file)

        stats_file = output_dir / "contents_extraction_stats.json"
        serializable_stats = {
            k: dict(v) if isinstance(v, Counter) else v
            for k, v in self.stats.items()
        }
        with open(stats_file, "w", encoding="utf-8") as f:
            json.dump(serializable_stats, f, ensure_ascii=False, indent=2)
        logger.info("Stats: %s", json.dumps(serializable_stats, indent=2))


def main() -> None:
    """Run contents entity extraction on MARC data."""
    input_file = Path("processed-data/filtered_data.csv")
    if not input_file.exists():
        input_file = Path("ner/processed-data/filtered_data.csv")
    if not input_file.exists():
        logger.error("Input file not found: %s", input_file)
        sys.exit(1)

    extractor = ContentsEntityExtractor(input_file)
    samples = extractor.process_dataset()
    extractor.save_results(samples, Path("processed-data"))


if __name__ == "__main__":
    main()
